name: 'Publish Github Actions'
description: 'Publishes Github action and tags release'
inputs:
  tag:
    description: The name of the git tag to use to tag the action.
    required: true

runs:
  using: "composite"
  steps:
    - run: |
        git config --global user.email "${{github.event.pusher.email}}"
        git config --global user.name "${{github.event.pusher.name}}"
      shell: bash
    - run: |
        # If there is a dist folder, commit it.
        if [ -d dist ]
        then
          git add -f dist || :
          git commit -m "Release for ${{ inputs.tag }}" || :
          # only commit node_modules if there is no dist.
        elif [ -d node_modules ]
        then
          git add -f node_modules || :
          git commit -m "Release for ${{ inputs.tag }}" || :
        fi
          
        git tag -f -a ${{ inputs.tag }} -m "Release for ${{ inputs.tag }}"
        git push -f --tags
      shell: bash